name: Terraform CI

on:
  workflow_dispatch:
  

  push:
    branches:
      - feature/*

  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Hello
        run: echo "Pipeline is running"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Check Terraform Version
        run: terraform version